kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-agent-role
  namespace: ${namespace}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-agent-rolebinding
  namespace: ${namespace}
subjects:
  - kind: ServiceAccount
    name: jenkins-agent
    namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-agent-role
  apiGroup: rbac.authorization.k8s.io
