repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: check-json
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
      - id: file-contents-sorter
        files: modules.yaml
  - repo: git://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        files: ^terraform/modules
      - id: terraform_docs_without_aggregate_type_defaults
        files: ^terraform/modules
      - id: terraform_tflint
        files: ^terraform/modules
      - id: terraform_tfsec
        files: ^terraform/modules
      - id: terragrunt_fmt
  - repo: git://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: helmlint
      - id: shellcheck
